---
title: "Multi repository overview"
output: 
  html_document:
    toc: true
params:
  dat: data.frame
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(rotspot)
library(ggplot2)
library(ggbeeswarm)
  
dat <- params$dat

n_pkgs <- length(unique(dat$pkg))
```

```{r}


dat[author %in% c("stefan.b.fleck@gmail.com", "FLECK Stefan", "Stefan", "stefan", "stefan.fleck", "Stefan Fleck - U", "s_fleck"), author := "Stefan Fleck"]


```


# By package

```{r, fig.height=1 + n_pkgs}
plot(dat) 

```

# By Author

```{r, fig.height=2 + length(unique(x$author))}
  dd <- dat[, .(
    commits = length(unique(hash))
  ), 
    by = c("date", "author")
  ]

  order <- dd[, .(commits = sum(commits)), by = "author"]
  data.table::setkeyv(order, "commits")
  dd[, author := factor(author, levels = rev(order$author))]


  ggplot2::ggplot(
    dd,
    ggplot2::aes(
      x = date,
      y = commits)
  ) +
    ggplot2::geom_bar(stat = "identity", color = "#B4DE2CFF") +
    ggplot2::theme_dark() +
    ggplot2::facet_grid(author ~ .) 
```


# Weekdays

```{r, fig.height=2 + length(unique(x$author))}

  dd <- dat[
    author == "Stefan Fleck" & lines_added > 5, 
    .(
      commits = length(unique(hash))
    ), 
      by = c("date", "author")
  ]

  dd[, wday := hammr::wday2(date)]
  
  pdat <- dd

  ggplot(
    pdat,
    aes(
      x = wday,
      group = wday,
      y = commits
    )
  ) + 
    geom_boxplot()



```


